name: Build Android Docker image

on:
  pull_request:
    branches:
      [
        dev,
        main,
        release/*,
        hotfix/*,
        bugfix/*,
        feature/*,
        chore/*,
        build/*,
        ci/*,
      ]
    paths:
      - ".docker/**"
      - "android/**"
      - "pubspec.yaml"
      - "pubspec.lock"
  workflow_dispatch:

jobs:
  build-android-docker:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Temporary workaround until firebase configs are added to CI
      - name: Comment out Google Play Services import
        shell: bash
        run: |
          sed -i 's/id .com\.google\.gms\.google-services./\/\/ id .com\.google\.gms\.google-services./' android/app/build.gradle
          echo "Google Play Services import commented out"

      - name: Build Android image
        env:
          GITHUB_API_PUBLIC_READONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional feedback provider secrets to embed dart-defines
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
          FEEDBACK_API_KEY: ${{ secrets.FEEDBACK_API_KEY }}
          FEEDBACK_PRODUCTION_URL: ${{ secrets.FEEDBACK_PRODUCTION_URL }}
          MATOMO_URL: ${{ secrets.MATOMO_URL }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID }}
        run: |
          chmod +x .docker/build.sh
          sh .docker/build.sh apk release

      - name: Compute short commit SHA
        id: vars
        shell: bash
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
  
      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: komodo-wallet-android-docker-${{ steps.vars.outputs.short_sha }}.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5
