# Deploys a preview build to Firebase Hosting when a pull request is opened, synchronized, or reopened
name: Deploy to Firebase Hosting on PR
run-name: ${{ github.actor }} is deploying a preview build to Firebase Hosting ðŸš€

on:
  pull_request:
    branches:
      - dev
      - main
      - release/*
  workflow_dispatch:

jobs:
  build_and_preview:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Shortify commit sha
        shell: bash
        run: echo "sha_short=$(echo ${GITHUB_SHA::7})" >> $GITHUB_OUTPUT
        id: shortify_commit

      - name: Get branch
        shell: bash
        run: echo "ref_short=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Get Preview Channel ID
        shell: bash
        run: echo "preview_channel_id=$(echo ${GITHUB_REF#*/})" >> $GITHUB_OUTPUT
        id: get_preview_channel_id

      - name: Setup GH Actions
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Flutter and dependencies
        uses: ./.github/actions/flutter-deps

      - name: Fetch packages and generate assets
        uses: ./.github/actions/generate-assets
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optionally provide feedback service configuration if available
          FEEDBACK_API_KEY: ${{ secrets.FEEDBACK_API_KEY }}
          FEEDBACK_PRODUCTION_URL: ${{ secrets.FEEDBACK_PRODUCTION_URL }}
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
          # Matomo analytics configuration (optional). If not provided, analytics will be disabled in CI.
          MATOMO_URL: ${{ secrets.MATOMO_URL }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID }}
          ANALYTICS_DISABLED: true

      - name: Validate build
        uses: ./.github/actions/validate-build

      - name: Deploy Komodo Wallet web feature preview (Expires in 7 days)
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOMODO_WALLET_OFFICIAL }}"
          channelId: "${{ steps.get_preview_channel_id.outputs.preview_channel_id }}"
          target: walletrc
          expires: 7d
          projectId: komodo-wallet-official

      - name: Deploy Komodo Wallet Web dev preview (`dev` branch)
        if: github.ref == 'refs/heads/dev' && github.event_name != 'workflow_dispatch'
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOMODO_WALLET_OFFICIAL }}"
          channelId: dev-preview
          target: walletrc
          projectId: komodo-wallet-official
