# Runs unit tests on PRs to ensure the app is working as expected
name: Run unit test on PR
run-name: ${{ github.actor }} is running unit tests on PR ðŸš€

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_tests:
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Setup GH Actions
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Flutter and dependencies
        uses: ./.github/actions/flutter-deps

      - name: Fetch packages and generate assets
        uses: ./.github/actions/generate-assets
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate build
        uses: ./.github/actions/validate-build

      - name: Test unit_test (unix)
        id: unit_tests
        continue-on-error: false
        timeout-minutes: 15
        env:
          GITHUB_API_PUBLIC_READONLY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          flutter test test_units/main.dart

      - name: Generate unit test coverage report
        id: unit_test_coverage
        timeout-minutes: 15
        uses: ./.github/actions/code-coverage
        with:
          test_file: "test_units/main.dart"
