# Rule for running static analysis and code formatting checks on all PRs
# Runs static analysis and code formatting checks on all PRs to ensure the codebase is clean and consistent
name: Validate Code Guidelines
run-name: ${{ github.actor }} is validating code guidelines ðŸš€

on:
  pull_request:
    branches:
      - "*"

jobs:
  validate_code_guidelines:
    if: false
    runs-on: ubuntu-latest

    steps:
      - name: Setup GH Actions
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Flutter and dependencies
        uses: ./.github/actions/flutter-deps

      - name: Fetch packages and generate assets
        uses: ./.github/actions/generate-assets
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate dart code
        run: |
          flutter analyze
          # Currently skipped due to many changes. Will be enabled in the future after doing full sweep of the codebase
          # dart format --set-exit-if-changed .
